class item extends entity{
    constructor(layer,x,y,type){
        super(layer,x,y,{main:1,trigger:true,speed:15})
        this.type=type
        this.setupValues()
    }
    setupValues(){
        this.direction=random(0,360)
        this.process={main:0}
        this.held=false
        this.process=[]
        for(let a=0,la=types.item[type].process.length;a<la;a++){
            this.process.push({type:types.item[type].process[a][0],main:0,goal:types.item[type].process[a][1]})
        }
        this.name=types.wall[this.type].name
    }
    display(level,layer=this.layer){
        switch(level){
            case 0:
                layer.push()
                layer.translate(this.position.x,this.position.y)
                layer.rotate(this.direction)
                layer.noStroke()
                switch(this.name){
                    case 'Plate':
                        layer.fill(220,this.fade.main)
                        layer.ellipse(0,0,24)
                        layer.fill(200,this.fade.main)
                        layer.ellipse(0,0,20)
                    break
                }
                /*switch(this.type){
                    case 1:
                        layer.fill(220,220,160,this.fade.main)
                        layer.ellipse(0,0,12)
                    break
                    case 2:
                        layer.stroke(180,100,80,this.fade.main)
                        layer.strokeWeight(1)
                        layer.line(-3,-1,0,-4)
                        layer.line(3,-1,0,-4)
                        layer.noStroke()
                        layer.fill(200,0,80,this.fade.main)
                        layer.ellipse(-3.5,1,6)
                        layer.ellipse(3.5,1,6)
                        layer.fill(240,80,120,this.fade.main)
                        layer.ellipse(-3.5,1,4)
                        layer.ellipse(3.5,1,4)
                    break
                    case 3:
                        layer.fill(220,220,160,this.fade.main)
                        layer.ellipse(0,0,16)
                        layer.fill(200,180,120,this.fade.main)
                        layer.ellipse(0,0,13)
                        layer.stroke(220,220,160,this.fade.main)
                        layer.strokeWeight(1.5)
                        layer.line(0,-7.25,0,7.25)
                        layer.line(-7.25,0,7.25,0)
                        layer.line(-3.25,-6,-3.25,6)
                        layer.line(3.25,-6,3.25,6)
                        layer.line(-6,-3.25,6,-3.25)
                        layer.line(-6,3.25,6,3.25)
                    break
                    case 4:
                        layer.fill(220,220,160,this.fade.main)
                        layer.ellipse(0,0,16)
                        layer.fill(200,180,120,this.fade.main)
                        layer.ellipse(0,0,13)
                        layer.stroke(180,100,80,this.fade.main)
                        layer.strokeWeight(1)
                        layer.line(-3,-1,0,-4)
                        layer.line(3,-1,0,-4)
                        layer.noStroke()
                        layer.fill(200,0,80,this.fade.main)
                        layer.ellipse(-3.5,1,6)
                        layer.ellipse(3.5,1,6)
                        layer.fill(240,80,120,this.fade.main)
                        layer.ellipse(-3.5,1,4)
                        layer.ellipse(3.5,1,4)
                        layer.stroke(220,220,160,this.fade.main)
                        layer.strokeWeight(1.5)
                        layer.line(0,-7.25,0,7.25)
                        layer.line(-7.25,0,7.25,0)
                        layer.line(-3.25,-6,-3.25,6)
                        layer.line(3.25,-6,3.25,6)
                        layer.line(-6,-3.25,6,-3.25)
                        layer.line(-6,3.25,6,3.25)
                    break
                    case 5:
                        layer.fill(200,180,120,this.fade.main)
                        layer.ellipse(0,0,16)
                        layer.fill(160,0,60,this.fade.main)
                        layer.ellipse(0,0,13)
                        layer.stroke(200,180,120,this.fade.main)
                        layer.strokeWeight(1.5)
                        layer.line(0,-7.25,0,7.25)
                        layer.line(-7.25,0,7.25,0)
                        layer.line(-3.25,-6,-3.25,6)
                        layer.line(3.25,-6,3.25,6)
                        layer.line(-6,-3.25,6,-3.25)
                        layer.line(-6,3.25,6,3.25)
                    break
                    case 6:
                        layer.fill(30,this.fade.main)
                        layer.ellipse(0,0,16)
                        layer.fill(0,this.fade.main)
                        layer.ellipse(0,0,13)
                        layer.stroke(30,this.fade.main)
                        layer.strokeWeight(1.5)
                        layer.line(0,-7.25,0,7.25)
                        layer.line(-7.25,0,7.25,0)
                        layer.line(-3.25,-6,-3.25,6)
                        layer.line(3.25,-6,3.25,6)
                        layer.line(-6,-3.25,6,-3.25)
                        layer.line(-6,3.25,6,3.25)
                    break
                    case 7:
                        layer.fill(220,this.fade.main)
                        layer.ellipse(0,0,24)
                        layer.fill(200,this.fade.main)
                        layer.ellipse(0,0,20)
                        layer.fill(200,180,120,this.fade.main)
                        layer.ellipse(0,0,16)
                        layer.fill(160,0,60,this.fade.main)
                        layer.ellipse(0,0,13)
                        layer.stroke(200,180,120,this.fade.main)
                        layer.strokeWeight(1.5)
                        layer.line(0,-7.25,0,7.25)
                        layer.line(-7.25,0,7.25,0)
                        layer.line(-3.25,-6,-3.25,6)
                        layer.line(3.25,-6,3.25,6)
                        layer.line(-6,-3.25,6,-3.25)
                        layer.line(-6,3.25,6,3.25)
                    break
                    case 8:
                        layer.fill(220,this.fade.main)
                        layer.ellipse(0,0,24)
                        layer.fill(200,this.fade.main)
                        layer.ellipse(0,0,20)
                        layer.fill(200,180,120,this.fade.main)
                        layer.ellipse(-4,0,5)
                        layer.ellipse(1,-4,3.5)
                        layer.fill(160,0,60,this.fade.main)
                        layer.ellipse(3.5,2,4)
                    break
                }*/
                layer.pop()
            break
        }
    }
    displayProcess(type){
        layer.push()
        layer.translate(this.position.x,this.position.y)
        for(let a=0,la=this.process.length;a<la;a++){
            if(this.process[a].type==type){
                layer.noStroke()
                layer.fill(40)
                layer.rect(0,-16,36,8,3)
                switch(this.process[a].type){
                    case 5:
                        layer.fill(240,20,20,this.fade.main)
                        layer.rect(-16.5*(1-this.process.main/this.process.goal),-16,33*this.process.main/this.process.goal,5,2)
                    break
                    default:
                        layer.fill(20,240,20,this.fade.main)
                        layer.rect(-16.5*(1-this.process.main/this.process.goal),-16,33*this.process.main/this.process.goal,5,2)
                    break
                }
            }
        }
        layer.pop()
    }
    update(parent){
        super.update()
        if(this.process.goal>0&&this.process.main>=this.process.goal){
        }
    }
}